import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";
import Providers from "./Providers";


const outift = localFont({
  src: '../../public/fonts/Outfit.ttf',
  variable: '--font-outfit'
})


const poppins = localFont({
  src: '../../public/fonts/Poppins.ttf',
  variable: '--font-poppins'
})

const poltwaski = localFont({
  src: '../../public/fonts/Poltwaski.ttf',
  variable: '--font-poltwaski'
})



export const metadata: Metadata = {
  title: "TUNECYCLE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outift.variable}
         ${poltwaski.variable}
         ${poppins.variable}
         font-poppins
        antialiased`}
      >
       <Providers>
        {children}
       </Providers>
      </body>
    </html>
  );
}